# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 532d911fec91cf9a83c18e25759236c50f74705cf4e1664fc4b6ccde3b2341493b6b5c3311e009b0160534a386c76a84146e823102abc7b3754caaa5d4d7178f

test:
  secret_key_base: 9723a1617b1bbeb8819e1592c1c4109c7f8e836c0830c1add6e18b4ac129da7091bdbfaca01d8114f8f36bcfc4494adc8b57524f74e416c7e9d39a8bcb7e01f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
